name: test-terraform
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.2
      - name: Apply Terraform
        run: |
          terraform init
          terraform apply -auto-approve
      - name: Display Function Output
        run: |
          python -c "from hello_world import hello_world; print(hello_world())"
      - name: Display Output
        run: |
          terraform output